version: '3.8'

services:
  web:
    build: .
    container_name: techify-store
    command: gunicorn --bind 0.0.0.0:8000 techify-store.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=1  