# Generated by Django 5.1.4 on 2025-01-12 09:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[(accounts.models.UserStatus['ACTIVE'], 'active'), (accounts.models.UserStatus['INACTIVE'], 'inactive'), (accounts.models.UserStatus['BLOCKED'], 'blocked')], default='active', max_length=100),
        ),
    ]
