# Generated by Django 5.1.4 on 2025-01-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createBy', models.CharField(max_length=255)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('deleteBy', models.CharField(blank=True, max_length=255, null=True)),
                ('deleteAt', models.DateTimeField(blank=True, null=True)),
                ('accountId', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('notes', models.TextField()),
                ('method', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
