# Generated by Django 5.1.4 on 2025-01-12 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountdetail'),
        ('orders', '0003_remove_order_createat_remove_order_createby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='accountId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountdetail'),
        ),
    ]
