# Generated by Django 5.1.4 on 2025-01-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_orderdetail_orderid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="method",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
    ]
