# Generated by Django 5.1.4 on 2025-01-13 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_payment_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="order",
            name="redirect_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
