# Generated by Django 5.1.4 on 2025-01-13 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_order_uuid_order_redirect_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
