# Generated by Django 5.1.4 on 2025-01-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_order_order_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_uuid",
        ),
    ]
