# Generated by Django 5.1.4 on 2025-01-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_order_order_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_url",
        ),
        migrations.RemoveField(
            model_name="order",
            name="redirect_url",
        ),
    ]
