# Generated by Django 5.1.4 on 2025-01-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_remove_order_payment_url_remove_order_redirect_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="redirect_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
