# Generated by Django 5.1.4 on 2025-01-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_order_payment_url_order_redirect_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_url",
        ),
    ]
