# Generated by Django 5.1.4 on 2025-01-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_remove_order_payment_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_url",
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
