# Generated by Django 5.1.4 on 2025-01-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_order_payment_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=400, null=True),
        ),
    ]
